import Head from 'next/head'
import Navbar from '../components/Navbar'
import HeroSection from './HeroSection'
import AboutMe from './AboutMe'
import Projects from './Projects'
import Certifications from './Certifications'
import Contact from './Contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className='selection:bg-neutral-200 bg-neutral-100'>
      <Head>
        <title>Nicolle&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon-rounded.ico" />
      </Head>

      <Navbar />
      <HeroSection />
      <AboutMe />
      <Projects />
      <Certifications />
      <Contact />
      <Footer />

    </div>
  )
}
