import Head from 'next/head'
import Navbar from '../components/Navbar'
import HeroSection from './HeroSection'
import AboutMe from './AboutMe'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-rounded.ico" />
      </Head>

      <Navbar />
      <HeroSection />
      <AboutMe />

    </div>
  )
}
