import Head from 'next/head'
import Navbar from './components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-rounded.ico" />
      </Head>

      <Navbar/>

    </div>
  )
}
